"""Add table LightingPost

Revision ID: a4ac4092b249
Revises: 
Create Date: 2025-12-15 16:35:04.982742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4ac4092b249'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lighting_posts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('lamp_type', sa.String(), nullable=False),
    sa.Column('wattage', sa.Integer(), nullable=False),
    sa.Column('voltage', sa.Integer(), nullable=False),
    sa.Column('needs_repair', sa.Boolean(), nullable=False),
    sa.Column('last_maintenance', sa.Date(), nullable=True),
    sa.Column('installation_date', sa.Date(), nullable=True),
    sa.Column('hours_in_operation', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lighting_posts')
    # ### end Alembic commands ###
